export const CART_ACTION_TYPES = {
    SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
    SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
    SET_CART_COUNT: 'cart/SET_CART_COUNT',
    SET_CART_TOTAL: 'cart/SET_CART_TOTAL',
    ADD_ITEM: 'cart/ADD_ITEM',
    REMOVE_ITEM: 'cart/REMOVE_ITEM',
    CLEAR_CART_ITEMS: 'cart/CLEAR_CART_ITEMS',
    REMOVE_ALL_OF_PRODUCT_FROM_CART: 'cart/REMOVE_ALL_OF_PRODUCT_FROM_CART',
    TOGGLE_CART_HIDDEN: 'cart/TOGGLE_CART_HIDDEN',
    UPDATE_PRICES: 'cart/UPDATE_PRICES'
}